version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "https://s3.console.aws.amazon.com/s3/buckets/shopingcart-s3-bucket?region=us-east-1&tab=properties"
        BUILD_FOLDER: "build"
phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - npm run build
artifacts:
    files:
        - '**/*'
    base-directory: 'build*'
    discard-paths: yes
